const STORAGE_KEY="employeePayrollList";
let employeePayrollList=getEmployeePayrollDataFromLocalStorage();
document.addEventListener("DOMContentLoaded",()=>{document.getElementById("addEmployeeButton").addEventListener("click",()=>location.href="add-employee.html");populateDepartmentFilter();displayEmployeeCount();displayEmployeePayrollDetails(employeePayrollList);document.getElementById("departmentFilter").addEventListener("change",filterByDepartment)});
function displayEmployeePayrollDetails(employees){const tableBody=document.getElementById("employeeTableBody");if(!employees.length){tableBody.innerHTML=`<tr><td colspan="8" class="empty-row">No Employee Payroll Details Found</td></tr>`;return}tableBody.innerHTML="";for(let employee of employees){tableBody.innerHTML+=`<tr><td>${employee._profilePic?`<img class="profile-pic" src="${employee._profilePic}" alt="Profile">`:`<div class="no-profile">${getInitials(employee._name)}</div>`}</td><td><strong>${escapeHtml(employee._name)}</strong></td><td>${escapeHtml(employee._gender||"-")}</td><td><span class="department-tag">${escapeHtml(employee._department||"-")}</span></td><td class="salary">₹${Number(employee._salary||0).toLocaleString("en-IN")}</td><td>${escapeHtml(employee._startDate||"-")}</td><td>${employee._benefits?.length?employee._benefits.map(b=>`<span class="benefit-tag">${escapeHtml(b)}</span>`).join(""):"-"}</td><td>${escapeHtml(employee._notes||"-")}</td></tr>`}}
function populateDepartmentFilter(){const f=document.getElementById("departmentFilter"),d=[];for(let e of employeePayrollList)if(e._department&&!d.includes(e._department))d.push(e._department);d.sort();for(let x of d)f.innerHTML+=`<option value="${escapeHtml(x)}">${escapeHtml(x)}</option>`}
function filterByDepartment(e){const d=e.target.value;document.getElementById("departmentSummary").textContent=d==="ALL"?"All Departments":`${d} Department`;displayEmployeePayrollDetails(d==="ALL"?employeePayrollList:employeePayrollList.filter(x=>x._department===d))}
function getEmployeePayrollDataFromLocalStorage(){const data=localStorage.getItem(STORAGE_KEY);if(!data)return[];try{return JSON.parse(data)}catch(e){console.error(e);return[]}}
function displayEmployeeCount(){document.getElementById("employeeCount").textContent=employeePayrollList.length}
function getInitials(n){return n?.trim().split(/\s+/).slice(0,2).map(x=>x[0].toUpperCase()).join("")||"EP"}
function escapeHtml(v){return String(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
